event_homepage:
    pattern:  /hello/{name}/{count}
    defaults: { _controller: EventBundle:Default:index }

event_homehome:
    pattern: /
    defaults: { _controller: EventBundle:Default:home }

EventBundle_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /event

